### ISSUE TITLE
Class "Pusher\Pusher" not found error during installation of namu/wirechat

### ISSUE THREAD

**Issue by badrshs** [namumakwembo/wirechat#19]
### Package Version

latest

### Laravel Version

v11

### Livewire Version

^3.5

### PHP Version

PHP 8.2.12

### Tailwind CSS Version

v3.4

### Problem description

When installing the namu/wirechat package in Laravel 11, the package:discover command fails with the following error:

```
Error: Class "Pusher\Pusher" not found
  at vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastManager.php:341
```
This happens because the package indirectly triggers Laravel's broadcasting functionality, which attempts to initialize the Pusher driver.

### Expected behavior

The installation of `namu/wirechat `should complete successfully without breaking the application or requiring manual installation of additional dependencies.

### Steps to reproduce

just ` composer require namu/wirechat` as what doc said 

### Relevant log output

```shell
composer require namu/wirechat
./composer.json has been updated
Running composer update namu/wirechat
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking namu/wirechat (v0.0.6)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading namu/wirechat (v0.0.6)
  - Installing namu/wirechat (v0.0.6): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error

  Class "Pusher\Pusher" not found

  at vendor\laravel\framework\src\Illuminate\Broadcasting\BroadcastManager.php:341
    337▕                 $config['client_options'] ?? [],
    338▕             ),
    339▕         );
    340▕
  ➜ 341▕         $pusher = new Pusher(
    342▕             $config['key'],
    343▕             $config['secret'],
    344▕             $config['app_id'],
    345▕             $config['options'] ?? [],

  1   vendor\laravel\framework\src\Illuminate\Broadcasting\BroadcastManager.php:319
      Illuminate\Broadcasting\BroadcastManager::pusher()

  2   vendor\laravel\framework\src\Illuminate\Broadcasting\BroadcastManager.php:308
      Illuminate\Broadcasting\BroadcastManager::createPusherDriver()

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by badrshs** [comment]
Just to add a workaround here, I installed Pusher and then installed this package, and it worked

`composer require pusher/pusher-php-server
`

**Comment by namumakwembo** [comment]
> Just to add a workaround here, I installed Pusher and then installed this package, and it worked
> 
> ```
> composer require pusher/pusher-php-server
> 
> composer require namu/wirechat
> ```

Thank you for the update! I’d like to clarify that Wirechat does not require Pusher during installation. It seems there might have been a misconfiguration in your broadcasting setup. I'm glad to hear you were able to fix it. If you have any further questions or run into other issues, feel free to reach out. 😊

**Comment by namumakwembo** [comment]
> I was playing around and I found another issues .. Just to let you know 😉
> 
> the text has to be deleted after typing the message + the icons has issues and I can't open it .
> 
> ![chrome_9rEQwDMzB8](https://private-user-images.githubusercontent.com/26596347/396695458-c23067b7-bfea-43ac-a290-1267ae599745.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDgzMDcsIm5iZiI6MTczNDUwODAwNywicGF0aCI6Ii8yNjU5NjM0Ny8zOTY2OTU0NTgtYzIzMDY3YjctYmZlYS00M2FjLWEyOTAtMTI2N2FlNTk5NzQ1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA3NDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNmU2N2ZjYjZjMWQ2MWRmOTU2ZTU4ZmRjMmE3YjRmNjJiZjg5MGUyOWQzMTZiNTIyOGM1NjY0OGQzZGYyNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0FeVIq0RKLZcQiGAZF7gJ97dXuAOBeUXGUPfRymONHk)  
 
Could you share any Laravel error logs or JavaScript console logs to help identify the problem?

Also, have you manually installed Alpine.js (e.g., by importing it separately)? If so, this could cause conflicts since Livewire includes Alpine.js by default. Let me know so we can address it.

**Comment by Muhammed2024Salama** [comment]
1. Install the Pusher PHP SDK
composer require pusher/pusher-php-server

2. Verify Broadcasting Configuration
config/broadcasting.php

'pusher' => [
    'driver' => 'pusher',
    'key' => env('PUSHER_APP_KEY'),
    'secret' => env('PUSHER_APP_SECRET'),
    'app_id' => env('PUSHER_APP_ID'),
    'options' => [
        'cluster' => env('PUSHER_APP_CLUSTER'),
        'useTLS' => true,
    ],
],
Ensure your .env file includes the necessary Pusher configuration values:

PUSHER_APP_ID=your-app-id
PUSHER_APP_KEY=your-app-key
PUSHER_APP_SECRET=your-app-secret
PUSHER_APP_CLUSTER=your-app-cluster

php artisan config:cache

Reinstall the namu/wirechat package to verify everything works as expected:

composer require namu/wirechat

**Comment by zsoltjanes** [comment]
I had the same issue, check your .env file, and set your BROADCAST_DRIVER varilable (BROADCAST_DRIVER=log).
