### ISSUE TITLE
Morph User Class is not assigned correctly

### ISSUE THREAD

**Issue by tony98ms** [namumakwembo/wirechat#24]
### Package Version

v0.0.7

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

PHP 8.2

### Tailwind CSS Version

v3.3.0

### Problem description

Hi, thank you for this awesome package, i am using in a project, but i have some bugs with polymorphic relationship of User model. 
I have a ServiceProvider where used the method Relation::MorphMap, for example:

```php
 Relation::MorphMap([
    'user' => User::class,
 ]);
```

But when I create any process with this package, in my database, the morph user model is registered as `App\\Models\\User`, but it should be registered as `user`.

This causes a problem if I want to use the relationships outside the chat UI.

### Expected behavior

For example in this case
```php
// Namu\WireChat\Models\Conversation

  public function addParticipant(Model $user, ParticipantRole $role = ParticipantRole::PARTICIPANT, bool $undoAdminRemovalAction = false): Participant
    {
        // Check if the participant already exists (with or without global scopes)

      
        $participant = $this->participants()
            ->withoutGlobalScopes()
            ->where('participantable_id', $user->id)
            ->where('participantable_type', get_class($user))  // This register model as "App\\Models\\User",
            ->first();
         
         $participant = $this->participants()
            ->withoutGlobalScopes()
            ->where('participantable_id', $user->id)
            ->where('participantable_type', $user->getMorphClass())    //This register model as 'user', correctly 
            ->first();
   }
```
This causes a problem if I want to use the relationships outside the chat UI.
This happens with all relationships or everywhere where `get_class($user)` or similar is used.

### Steps to reproduce

Can be reproduced in any environment

**Comment by namumakwembo** [comment]
fixed #25
